name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: AwesomeHamster/workflows/.github/workflows/build.yml@master
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    with:
      lint: true
      test: true
