name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    uses: AwesomeHamster/workflows/.github/workflows/publish.yml@master
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    with:
      lint: true
      test: true
      yarn-no-immutable: true
      npm-token: ${{ secrets.NPM_TOKEN }}
      test-before-publish: true
