name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AwesomeHamster/actions-test@master
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        with:
          install-peer: >
            koishi
            koishi-plugin-puppeteer
          test: |
            yarn lint
            yarn test
